apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: g0vsbpd7k-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/g0vsbpd7k-dotnet-basic